// ============================================
// MOCK DATA FOR CATEGORIES & SERVICES
// ============================================

import { Category, ServiceProvider } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Residential Carpentry',
    slug: 'residential-carpentry',
    description: 'Expert carpenters for home projects',
    icon: '🔨',
    services_count: 145,
    color: '#E8B4B8',
  },
  {
    id: 'cat-2',
    name: 'Electrical Services',
    slug: 'electrical-services',
    description: 'Licensed electricians for all electrical work',
    icon: '⚡',
    services_count: 203,
    color: '#FFE5B4',
  },
  {
    id: 'cat-3',
    name: 'Plumbing',
    slug: 'plumbing',
    description: 'Professional plumbers for repairs and installations',
    icon: '🔧',
    services_count: 178,
    color: '#B4D7E8',
  },
  {
    id: 'cat-4',
    name: 'Painting & Decoration',
    slug: 'painting-decoration',
    description: 'Transform your space with professional painters',
    icon: '🎨',
    services_count: 167,
    color: '#D4B4E8',
  },
  {
    id: 'cat-5',
    name: 'Cleaning Services',
    slug: 'cleaning-services',
    description: 'Reliable cleaning professionals for home and office',
    icon: '🧹',
    services_count: 289,
    color: '#B4E8D4',
  },
  {
    id: 'cat-6',
    name: 'Moving & Delivery',
    slug: 'moving-delivery',
    description: 'Fast and safe moving and delivery services',
    icon: '📦',
    services_count: 134,
    color: '#E8D4B4',
  },
  {
    id: 'cat-7',
    name: 'Tech Support',
    slug: 'tech-support',
    description: 'IT professionals for hardware and software issues',
    icon: '💻',
    services_count: 198,
    color: '#B4C8E8',
  },
  {
    id: 'cat-8',
    name: 'Garden & Landscaping',
    slug: 'garden-landscaping',
    description: 'Create beautiful outdoor spaces',
    icon: '🌱',
    services_count: 156,
    color: '#C8E8B4',
  },
];


// Mock Service Providers
export const MOCK_SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: 'sp-1',
    professionalName: 'John Kamau Furniture Works',
    serviceName: 'Custom Furniture & Assembly',
    banner: '/service-banners/furniture-banner.jpg',
    logo: '/service-logos/jk-furniture.jpg',
    description: 'Expert furniture assembly and custom woodwork with 10+ years experience',
    catchphrase: 'Crafting quality furniture for your home',
    category_id: 'cat-1',
    category_name: 'Residential Carpentry',
    price: 2500,
    priceType: 'fixed',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Westlands',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 3.2,
    },
    open_hours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.8,
    review_count: 127,
    is_verified: true,
    is_available_now: true,
    currency: 'KES',
  },
  {
    id: 'sp-2',
    professionalName: 'Wanjiku Electrical Solutions',
    serviceName: 'Home & Commercial Wiring',
    banner: '/service-banners/electrical-banner.jpg',
    logo: '/service-logos/wanjiku-electric.jpg',
    description: 'Licensed electrician specializing in home and commercial electrical installations',
    catchphrase: 'Powering homes safely across Nairobi',
    category_id: 'cat-2',
    category_name: 'Electrical Services',
    price: 5000,
    priceType: 'hourly',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Kilimani',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 5.1,
    },
    open_hours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '16:00' },
      sunday: { open: '10:00', close: '14:00' },
    },
    rating: 4.9,
    review_count: 203,
    is_verified: true,
    is_available_now: false,
    currency: 'KES',
  },
  {
    id: 'sp-3',
    professionalName: 'Quick Fix Plumbing',
    serviceName: 'Emergency Plumbing Services',
    banner: '/service-banners/plumbing-banner.jpg',
    logo: '/service-logos/quickfix-plumbing.jpg',
    description: 'Fast and reliable plumbing repairs and installations available 24/7',
    catchphrase: 'No leak too small, no job too big',
    category_id: 'cat-3',
    category_name: 'Plumbing',
    price: 1500,
    priceType: 'fixed',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Karen',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 8.3,
    },
    open_hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    rating: 4.7,
    review_count: 156,
    is_verified: true,
    is_available_now: true,
    currency: 'KES',
  },
  {
    id: 'sp-4',
    professionalName: 'Colors & Designs Painting',
    serviceName: 'Interior & Exterior Painting',
    banner: '/service-banners/painting-banner.jpg',
    logo: '/service-logos/colors-designs.jpg',
    description: 'Professional painting services for residential and commercial properties',
    catchphrase: 'Bringing color to your life',
    category_id: 'cat-4',
    category_name: 'Painting & Decoration',
    priceType: 'negotiable',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Parklands',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 4.5,
    },
    open_hours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '17:00' },
      friday: { open: '08:00', close: '17:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.6,
    review_count: 89,
    is_verified: true,
    is_available_now: true,
    currency: 'KES',
  },
  {
    id: 'sp-5',
    professionalName: 'Sparkle Clean Services',
    serviceName: 'Deep Cleaning Specialists',
    banner: '/service-banners/cleaning-banner.jpg',
    logo: '/service-logos/sparkle-clean.jpg',
    description: 'Thorough home and office cleaning with eco-friendly products',
    catchphrase: 'Making your space sparkle',
    category_id: 'cat-5',
    category_name: 'Cleaning Services',
    price: 3000,
    priceType: 'fixed',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Lavington',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 6.2,
    },
    open_hours: {
      monday: { open: '06:00', close: '20:00' },
      tuesday: { open: '06:00', close: '20:00' },
      wednesday: { open: '06:00', close: '20:00' },
      thursday: { open: '06:00', close: '20:00' },
      friday: { open: '06:00', close: '20:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    rating: 4.9,
    review_count: 234,
    is_verified: true,
    is_available_now: true,
    currency: 'KES',
  },
  {
    id: 'sp-6',
    professionalName: 'Swift Movers Kenya',
    serviceName: 'Professional Moving Services',
    banner: '/service-banners/moving-banner.jpg',
    logo: '/service-logos/swift-movers.jpg',
    description: 'Reliable and careful moving services for homes and offices',
    catchphrase: 'Moving made easy',
    category_id: 'cat-6',
    category_name: 'Moving & Delivery',
    priceType: 'negotiable',
    location: {
      lat: -1.2921,
      lng: 36.8219,
      address: 'Industrial Area',
      city: 'Nairobi',
      country: 'Kenya',
      distance: 7.8,
    },
    open_hours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.8,
    review_count: 178,
    is_verified: true,
    is_available_now: false,
    currency: 'KES',
  },
];