// ============================================
// MOCK DATA FOR CATEGORIES & SERVICES
// ============================================

import { Category, Service } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Residential Carpentry',
    slug: 'residential-carpentry',
    description: 'Expert carpenters for home projects',
    icon: '🔨',
    serviceCount: 145,
    color: '#E8B4B8',
  },
  {
    id: 'cat-2',
    name: 'Electrical Services',
    slug: 'electrical-services',
    description: 'Licensed electricians for all electrical work',
    icon: '⚡',
    serviceCount: 203,
    color: '#FFE5B4',
  },
  {
    id: 'cat-3',
    name: 'Plumbing',
    slug: 'plumbing',
    description: 'Professional plumbers for repairs and installations',
    icon: '🔧',
    serviceCount: 178,
    color: '#B4D7E8',
  },
  {
    id: 'cat-4',
    name: 'Painting & Decoration',
    slug: 'painting-decoration',
    description: 'Transform your space with professional painters',
    icon: '🎨',
    serviceCount: 167,
    color: '#D4B4E8',
  },
  {
    id: 'cat-5',
    name: 'Cleaning Services',
    slug: 'cleaning-services',
    description: 'Reliable cleaning professionals for home and office',
    icon: '🧹',
    serviceCount: 289,
    color: '#B4E8D4',
  },
  {
    id: 'cat-6',
    name: 'Moving & Delivery',
    slug: 'moving-delivery',
    description: 'Fast and safe moving and delivery services',
    icon: '📦',
    serviceCount: 134,
    color: '#E8D4B4',
  },
  {
    id: 'cat-7',
    name: 'Tech Support',
    slug: 'tech-support',
    description: 'IT professionals for hardware and software issues',
    icon: '💻',
    serviceCount: 198,
    color: '#B4C8E8',
  },
  {
    id: 'cat-8',
    name: 'Garden & Landscaping',
    slug: 'garden-landscaping',
    description: 'Create beautiful outdoor spaces',
    icon: '🌱',
    serviceCount: 156,
    color: '#C8E8B4',
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'serv-1',
    name: 'Furniture Assembly',
    categoryId: 'cat-1',
    categoryName: 'Residential Carpentry',
    description: 'Professional furniture assembly services',
    price: 2500,
    priceType: 'fixed',
    icon: '🪑',
  },
  {
    id: 'serv-2',
    name: 'Home Wiring',
    categoryId: 'cat-2',
    categoryName: 'Electrical Services',
    description: 'Complete home electrical wiring',
    price: 5000,
    priceType: 'hourly',
    icon: '💡',
  },
  {
    id: 'serv-3',
    name: 'Pipe Repair',
    categoryId: 'cat-3',
    categoryName: 'Plumbing',
    description: 'Fix leaking and damaged pipes',
    price: 1500,
    priceType: 'fixed',
    icon: '🚿',
  },
  {
    id: 'serv-4',
    name: 'Interior Painting',
    categoryId: 'cat-4',
    categoryName: 'Painting & Decoration',
    description: 'Professional interior wall painting',
    priceType: 'negotiable',
    icon: '🖌️',
  },
  {
    id: 'serv-5',
    name: 'Deep House Cleaning',
    categoryId: 'cat-5',
    categoryName: 'Cleaning Services',
    description: 'Thorough cleaning of entire home',
    price: 3000,
    priceType: 'fixed',
    icon: '✨',
  },
  {
    id: 'serv-6',
    name: 'Office Relocation',
    categoryId: 'cat-6',
    categoryName: 'Moving & Delivery',
    description: 'Professional office moving services',
    priceType: 'negotiable',
    icon: '🏢',
  },
];